---
version: "2.4"
services:
  fluentd:
    image: ${FLUENTD_IMAGE}
    ports:
      - 127.0.0.1:24224:24224
    #            - 24224:24224/udp
    volumes:
      - ./fluentd/etc:/fluentd/etc
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "2"
networks:
  net:
    driver: bridge
