FROM fluent/fluentd:v1.11.5-1.0

USER root

RUN apk add --no-cache --update --virtual .build-deps \
	sudo build-base ruby-dev \
	&& sudo gem install fluent-plugin-elasticsearch \
	&& sudo gem install fluent-plugin-rewrite-tag-filter \
	&& sudo gem sources --clear-all \
	&& apk del .build-deps \
	&& rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

USER fluent